migrate.source.yaml:
  type: migrate_source
  label: 'YAML'
  mapping:
    path:
      type: string
      label: 'Path to the source CSV file'
    keys:
      type: sequence
      label: 'Column name(s) which represent the key uniquely identifying each record'
      sequence:
        type: string
        label: 'Key field'
    column_names:
      type: sequence
      label: 'Numeric key 0-based index of the columns in source CSV file'